version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node

volumes:
  esdata:
    external: true
